name: nashmi_admin_v2
description: "لوحة تحكم 2 - لوحة تحكم لإدارة الأفلام والمسلسلات والإعلانات"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Supabase
  supabase_flutter: ^2.8.3

  # UI Components
  flutter_launcher_icons: ^0.14.4
  file_picker: ^8.1.2
  image_picker: ^1.0.4
  cached_network_image: ^3.4.1
  fl_chart: ^0.71.0
  flutter_inappwebview: ^6.1.5

  # State Management
  get: ^4.6.6

  # Utils
  shared_preferences: ^2.3.0
  intl: ^0.20.2
  uuid: ^4.4.0

  # Google AdMob
  google_mobile_ads: ^5.1.0

  # New packages for modernization
  flutter_localizations:
    sdk: flutter
  csv: ^6.0.0
  intl_utils: ^2.8.7

  # Note: Firebase dependencies removed as admin app uses Supabase only

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/supabase_config.json

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
