// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase project.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyYour-Web-API-Key-Here',
    appId: '1:your-web-app-id:web:your-web-app-id',
    messagingSenderId: 'your-messaging-sender-id',
    projectId: 'nashmi-tf',
    authDomain: 'nashmi-tf.firebaseapp.com',
    storageBucket: 'nashmi-tf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyYour-Android-API-Key-Here',
    appId: '1:your-android-app-id:android:your-android-app-id',
    messagingSenderId: 'your-messaging-sender-id',
    projectId: 'nashmi-tf',
    storageBucket: 'nashmi-tf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyYour-iOS-API-Key-Here',
    appId: '1:your-ios-app-id:ios:your-ios-app-id',
    messagingSenderId: 'your-messaging-sender-id',
    projectId: 'nashmi-tf',
    storageBucket: 'nashmi-tf.appspot.com',
    iosBundleId: 'com.example.nashmiTf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyYour-macOS-API-Key-Here',
    appId: '1:your-macos-app-id:macos:your-macos-app-id',
    messagingSenderId: 'your-messaging-sender-id',
    projectId: 'nashmi-tf',
    storageBucket: 'nashmi-tf.appspot.com',
    iosBundleId: 'com.example.nashmiTf',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyYour-Windows-API-Key-Here',
    appId: '1:your-windows-app-id:web:your-windows-app-id',
    messagingSenderId: 'your-messaging-sender-id',
    projectId: 'nashmi-tf',
    authDomain: 'nashmi-tf.firebaseapp.com',
    storageBucket: 'nashmi-tf.appspot.com',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyYour-Linux-API-Key-Here',
    appId: '1:your-linux-app-id:web:your-linux-app-id',
    messagingSenderId: 'your-messaging-sender-id',
    projectId: 'nashmi-tf',
    authDomain: 'nashmi-tf.firebaseapp.com',
    storageBucket: 'nashmi-tf.appspot.com',
  );
}
