name: nashmi_tf
description: "نشمي TF - تطبيق لعرض الأفلام والمسلسلات"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Localization Support
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # State Management
  get: ^4.6.6

  # UI Components
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0

  # Video Player
  video_player: ^2.8.3
  chewie: ^1.7.5
  youtube_player_flutter: ^9.1.2
  flutter_inappwebview: ^6.1.5
  universal_platform: ^1.0.0+1
  webview_flutter: ^4.8.0
  webview_flutter_android: ^3.16.4
  webview_flutter_wkwebview: ^3.13.1

  # Firebase - Updated to compatible versions
  firebase_core: ^3.10.0
  cloud_firestore: ^5.6.0
  firebase_storage: ^12.3.0
  firebase_dynamic_links: ^6.0.0

  # Ads
  google_mobile_ads: ^4.0.0

  # Utils
  shared_preferences: ^2.2.2
  flutter_launcher_icons: ^0.14.4
  supabase_flutter: ^2.10.0
  file_picker: ^8.0.0+1
  get_it: ^8.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - assets/supabase_config.json

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
