// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDozQTlWu59_bVQWQdbtqlGJOmz__H6dBA',
    appId: '1:784161677453:web:882d183d80a7802ddb42c4',
    messagingSenderId: '784161677453',
    projectId: 'neshmitf-dashboard',
    authDomain: 'neshmitf-dashboard.firebaseapp.com',
    storageBucket: 'neshmitf-dashboard.firebasestorage.app',
    measurementId: '',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDozQTlWu59_bVQWQdbtqlGJOmz__H6dBA',
    appId: '1:784161677453:android:882d183d80a7802ddb42c4',
    messagingSenderId: '784161677453',
    projectId: 'neshmitf-dashboard',
    storageBucket: 'neshmitf-dashboard.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDozQTlWu59_bVQWQdbtqlGJOmz__H6dBA',
    appId: '1:784161677453:ios:882d183d80a7802ddb42c4',
    messagingSenderId: '784161677453',
    projectId: 'neshmitf-dashboard',
    storageBucket: 'neshmitf-dashboard.firebasestorage.app',
    iosBundleId: 'com.example.nashmi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDozQTlWu59_bVQWQdbtqlGJOmz__H6dBA',
    appId: '1:784161677453:macos:882d183d80a7802ddb42c4',
    messagingSenderId: '784161677453',
    projectId: 'neshmitf-dashboard',
    storageBucket: 'neshmitf-dashboard.firebasestorage.app',
    iosBundleId: 'com.example.nashmi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDozQTlWu59_bVQWQdbtqlGJOmz__H6dBA',
    appId: '1:784161677453:windows:882d183d80a7802ddb42c4',
    messagingSenderId: '784161677453',
    projectId: 'neshmitf-dashboard',
    authDomain: 'neshmitf-dashboard.firebaseapp.com',
    storageBucket: 'neshmitf-dashboard.firebasestorage.app',
    measurementId: '',
  );
}
